name = "wispy-boat-fb50"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "d682a04f4b4c4811b66876d23f4a5788" }
]
